import { pipeline, env } from '@xenova/transformers';

// Configure transformers context
env.allowLocalModels = false;
env.useBrowserCache = true;

class JobMatcher {
    constructor() {
        this.modelId = 'Xenova/all-MiniLM-L6-v2';
        this.extractor = null;
        this.jobDatabase = null;
        this.jobEmbeddings = null; // Pre-computed via generate_embeddings.js
        this.isInitialized = false;
    }

    async init(progressCallback) {
        if (this.isInitialized) return;

        try {
            // 1. Load the AI pipeline
            progressCallback?.("Loading AI Model (this may take a minute on first load)...");
            this.extractor = await pipeline('feature-extraction', this.modelId, {
                quantized: true,
                progress_callback: (info) => {
                    if (info.status === 'downloading' && progressCallback) {
                        progressCallback(`Downloading model: ${info.file} (${Math.round(info.progress)}%)`);
                    }
                }
            });

            // 2. Load JSONL dataset
            progressCallback?.("Loading Job Database...");
            const dbResponse = await fetch('/datasets/DTP_Database.jsonl');
            const dbText = await dbResponse.text();
            this.jobDatabase = dbText.split('\n')
                .filter(line => line.trim())
                .map(line => JSON.parse(line));

            // 3. Load pre-computed embeddings (generated by: node generate_embeddings.js)
            progressCallback?.("Loading Vector Index...");
            const idxResponse = await fetch('/datasets/pon_index.json');
            this.jobEmbeddings = await idxResponse.json();

            this.isInitialized = true;
            progressCallback?.("Initialization complete.");
        } catch (error) {
            console.error("Failed to initialize JobMatcher:", error);
            throw new Error("Failed to load matching engine. Please check your internet connection and try again.");
        }
    }

    async generateEmbedding(text) {
        if (!this.extractor) throw new Error("Model not initialized");
        const output = await this.extractor(text, { pooling: 'mean', normalize: true });
        return Array.from(output.data);
    }

    // Condense long CV text to focus on key skills and technologies
    // MiniLM model only reads ~256 tokens - this ensures key terms aren't lost
    preprocessCvText(cvText) {
        const text = cvText.toLowerCase();

        // Technical terms patterns to extract
        const techPatterns = [
            // Programming & frameworks
            /\b(python|javascript|typescript|java|php|golang|rust|ruby|swift|kotlin|dart|sql|html|css)\b/gi,
            /\b(laravel|django|flask|react|vue|angular|next\.?js|node\.?js|express|spring|\.net)\b/gi,
            /\b(tensorflow|pytorch|keras|scikit-learn|pandas|numpy|matplotlib|scipy|streamlit)\b/gi,
            // AI/ML terms
            /\b(machine learning|deep learning|nlp|natural language processing|computer vision)\b/gi,
            /\b(neural network|cnn|rnn|lstm|transformer|bert|gpt|llm|rag|fine-?tuning)\b/gi,
            /\b(classification|clustering|regression|supervised|unsupervised|reinforcement)\b/gi,
            /\b(embedding|tokenization|sentiment analysis|speech processing|ocr)\b/gi,
            /\b(mlops|model deployment|data pipeline|feature engineering|data science)\b/gi,
            // Data & DevOps
            /\b(mysql|postgresql|mongodb|redis|elasticsearch|kafka|docker|kubernetes)\b/gi,
            /\b(aws|azure|gcp|ci\/cd|git|github|linux|devops|cloud)\b/gi,
            // Roles & domains
            /\b(data scientist|data engineer|ai engineer|ml engineer|fullstack|backend|frontend)\b/gi,
            /\b(web scraping|api|rest|graphql|microservices|agile|scrum)\b/gi,
            /\b(cybersecurity|penetration testing|blockchain|iot|mobile)\b/gi,
        ];

        const foundTerms = new Set();
        techPatterns.forEach(pattern => {
            const matches = cvText.match(pattern);
            if (matches) matches.forEach(m => foundTerms.add(m.trim()));
        });

        // Also extract job titles and key phrases from the first few lines
        const firstLines = cvText.split('\n').slice(0, 15).join(' ');

        // Build focused text: first lines (summary) + all extracted technical terms
        const focusedText = firstLines + '. Skills: ' + [...foundTerms].join(', ');

        // Limit to ~250 words to stay within model context
        const words = focusedText.split(/\s+/).slice(0, 250);
        return words.join(' ');
    }

    cosineSimilarity(vecA, vecB) {
        let dotProduct = 0;
        let normA = 0;
        let normB = 0;
        for (let i = 0; i < vecA.length; i++) {
            dotProduct += vecA[i] * vecB[i];
            normA += vecA[i] * vecA[i];
            normB += vecB[i] * vecB[i];
        }
        return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
    }

    // Common generic words to ignore during keyword matching
    static STOP_WORDS = new Set([
        'and', 'the', 'for', 'with', 'from', 'into', 'using', 'based',
        'tools', 'tool', 'system', 'systems', 'process', 'processes',
        'management', 'manager', 'building', 'design', 'support',
        'strategy', 'development', 'developer', 'engineer', 'engineering',
        'analysis', 'analyst', 'implementation', 'basic', 'basics',
        'advanced', 'senior', 'junior', 'specialist', 'lead',
        'techniques', 'technique', 'concepts', 'concept',
        'best', 'practices', 'practice', 'custom', 'modern',
        'data', 'information', 'user', 'users', 'high', 'level',
        'real', 'time', 'end', 'testing', 'test', 'quality',
        'performance', 'integration', 'service', 'services',
        'application', 'applications', 'platform', 'selection',
        'documentation', 'training', 'evaluation', 'model', 'models'
    ]);

    isStopWord(word) {
        return JobMatcher.STOP_WORDS.has(word) || word.length < 3;
    }

    calculateKeywordScore(cvText, jobKeywords) {
        if (!jobKeywords) return 0;
        const content = cvText.toLowerCase();

        // Split by comma to get skill phrases
        const phrases = jobKeywords.split(',').map(k => k.trim().toLowerCase()).filter(k => k);
        if (phrases.length === 0) return 0;

        let totalPhrases = 0;
        let matchedScore = 0;

        phrases.forEach(phrase => {
            const cleanPhrase = phrase.replace(/[()\/&]/g, ' ').replace(/\s+/g, ' ').trim();

            // Extract meaningful (non-stop) words from the phrase
            const meaningfulWords = cleanPhrase.split(/\s+/).filter(w => !this.isStopWord(w));
            if (meaningfulWords.length === 0) return; // skip all-generic phrases

            totalPhrases++;

            // Check full phrase match first (highest value)
            if (cleanPhrase.length >= 6 && content.includes(cleanPhrase)) {
                matchedScore += 1.0;
                return;
            }

            // Check meaningful words - require at least 50% match for partial credit
            const hits = meaningfulWords.filter(w => content.includes(w)).length;
            const ratio = hits / meaningfulWords.length;
            if (ratio >= 0.5) {
                matchedScore += ratio * 0.6; // partial credit capped at 60% of full match
            }
        });

        return totalPhrases > 0 ? matchedScore / totalPhrases : 0;
    }

    calculateFieldScore(cvText, job) {
        const content = cvText.toLowerCase();

        // Check Area_Fungsi
        const area = (job.Area_Fungsi || '').toLowerCase();
        if (!area) return 0;

        // Full match
        if (content.includes(area)) return 1.0;

        // Word-level match (only meaningful words)
        const areaWords = area.split(/[\s&]+/).filter(w => !this.isStopWord(w));
        if (areaWords.length === 0) return 0;

        const hits = areaWords.filter(w => content.includes(w)).length;
        return hits / areaWords.length;
    }

    async findMatches(cvText, topK = 5) {
        if (!this.isInitialized) {
            throw new Error("Job Matcher is not initialized. Call init() first.");
        }

        // 1. Pre-process CV text to extract key terms (MiniLM only reads ~256 tokens)
        const processedCv = this.preprocessCvText(cvText);
        const cvEmbedding = await this.generateEmbedding(processedCv);

        // 2. Compute weighted scores
        const scoredJobs = [];
        for (let i = 0; i < this.jobDatabase.length; i++) {
            const job = this.jobDatabase[i];
            const jobVector = this.jobEmbeddings[i];

            // Semantic Score (85%) - Cosine Similarity from embeddings (already includes Kuk_Keywords)
            const semanticScore = this.cosineSimilarity(cvEmbedding, jobVector);

            // Field Score (15%) - Area_Fungsi relevance
            const fieldScore = this.calculateFieldScore(cvText, job);

            // Total Weighted Score
            const totalScore = (semanticScore * 0.85) + (fieldScore * 0.15);

            scoredJobs.push({
                index: i,
                totalScore: totalScore,
                breakdown: {
                    semantic: (semanticScore * 100).toFixed(1),
                    field: (fieldScore * 100).toFixed(1)
                }
            });
        }

        // 3. Sort by descending totalScore and get top K
        scoredJobs.sort((a, b) => b.totalScore - a.totalScore);
        const topMatches = scoredJobs.slice(0, topK);

        // 4. Map back to database records
        return topMatches.map(match => {
            const jobData = this.jobDatabase[match.index];
            return {
                ...jobData,
                matchScore: (match.totalScore * 100).toFixed(1),
                scoreBreakdown: match.breakdown
            };
        });
    }
}

// Expose the instance
window.JobMatcherEngine = new JobMatcher();
